#!/usr/bin/env bash
# NEXORA v2 — Deploy contracts to Stellar Testnet
# Usage: ./scripts/deploy.sh [testnet|mainnet]
set -euo pipefail

NETWORK=${1:-testnet}
HORIZON_URL="https://horizon-testnet.stellar.org"
[[ "$NETWORK" == "mainnet" ]] && HORIZON_URL="https://horizon.stellar.org"

echo "════════════════════════════════════════════════"
echo "  NEXORA v2 Contract Deployment"
echo "  Network: $NETWORK"
echo "════════════════════════════════════════════════"

# Check deps
command -v stellar >/dev/null || { echo "❌ stellar-cli not found"; exit 1; }
command -v cargo   >/dev/null || { echo "❌ cargo not found"; exit 1; }

# Generate & fund deployer key
echo ""
echo "▸ Setting up deployer identity..."
stellar keys generate nexora-deployer --network "$NETWORK" --overwrite 2>/dev/null || true
DEPLOYER_ADDR=$(stellar keys address nexora-deployer)
echo "  Address: $DEPLOYER_ADDR"

if [[ "$NETWORK" == "testnet" ]]; then
  echo "  Funding via Friendbot..."
  curl -s "https://friendbot.stellar.org?addr=$DEPLOYER_ADDR" > /dev/null
  echo "  ✓ Funded"
fi

# Build contracts
echo ""
echo "▸ Building WASM contracts..."
cargo build --target wasm32-unknown-unknown --release \
  -p event-ticket \
  -p marketplace \
  --quiet
echo "  ✓ Build complete"

# Optimize
echo "▸ Optimizing WASM..."
stellar contract optimize \
  --wasm target/wasm32-unknown-unknown/release/event_ticket.wasm 2>/dev/null || true
stellar contract optimize \
  --wasm target/wasm32-unknown-unknown/release/marketplace.wasm 2>/dev/null || true
echo "  ✓ Optimized"

# Deploy EventTicket
echo ""
echo "▸ Deploying EventTicket contract..."
EVENT_CONTRACT_ID=$(stellar contract deploy \
  --wasm target/wasm32-unknown-unknown/release/event_ticket.wasm \
  --source nexora-deployer \
  --network "$NETWORK")
echo "  EventTicket ID: $EVENT_CONTRACT_ID"

# Initialize EventTicket
echo "▸ Initializing EventTicket..."
stellar contract invoke \
  --id "$EVENT_CONTRACT_ID" \
  --source nexora-deployer \
  --network "$NETWORK" \
  -- initialize \
  --admin "$DEPLOYER_ADDR"
echo "  ✓ EventTicket initialized"

# Deploy Marketplace
echo ""
echo "▸ Deploying Marketplace contract..."
MARKETPLACE_ID=$(stellar contract deploy \
  --wasm target/wasm32-unknown-unknown/release/marketplace.wasm \
  --source nexora-deployer \
  --network "$NETWORK")
echo "  Marketplace ID: $MARKETPLACE_ID"

# Initialize Marketplace
echo "▸ Initializing Marketplace with EventTicket address..."
stellar contract invoke \
  --id "$MARKETPLACE_ID" \
  --source nexora-deployer \
  --network "$NETWORK" \
  -- initialize \
  --admin "$DEPLOYER_ADDR" \
  --event_contract "$EVENT_CONTRACT_ID"
echo "  ✓ Marketplace initialized"

# Create demo event
echo ""
echo "▸ Creating demo event on-chain..."
DEMO_TXN=$(stellar contract invoke \
  --id "$EVENT_CONTRACT_ID" \
  --source nexora-deployer \
  --network "$NETWORK" \
  -- create_event \
  --creator "$DEPLOYER_ADDR" \
  --price 100000000 \
  --capacity 500 \
  --royalty_bps 500 \
  --metadata_uri "ipfs://nexora-demo-summit-2025")
echo "  ✓ Demo event created (tx: $DEMO_TXN)"

# Save addresses to .env
cat > .env.contracts << EOF
# Auto-generated by deploy.sh — $(date)
VITE_NETWORK=$NETWORK
VITE_EVENT_CONTRACT=$EVENT_CONTRACT_ID
VITE_MARKETPLACE_CONTRACT=$MARKETPLACE_ID
VITE_DEPLOYER_ADDRESS=$DEPLOYER_ADDR
VITE_SOROBAN_RPC=https://soroban-$NETWORK.stellar.org
VITE_HORIZON_URL=$HORIZON_URL
EOF
echo ""
echo "  ✓ Addresses saved to .env.contracts"

# Summary
echo ""
echo "════════════════════════════════════════════════"
echo "  ✅ Deployment Complete!"
echo ""
echo "  EventTicket:  $EVENT_CONTRACT_ID"
echo "  Marketplace:  $MARKETPLACE_ID"
echo "  Network:      Stellar $NETWORK"
echo ""
echo "  Explorer:"
echo "  https://stellar.expert/explorer/$NETWORK/contract/$EVENT_CONTRACT_ID"
echo "════════════════════════════════════════════════"
